### ISSUE TITLE
New org token not doing much

### ISSUE THREAD

**Issue by danlester** [ideonate/gitpocket#43]
I added a completely unseen org PAT with a manual name because it couldn't be inferred.

However much I reload stuff it never seems to pick up that orgs repos.

Maybe there's a problem with the token but either way it would be good to see an error somewhere even if next to it's token listed in account page, or in the repo filter (say No repos if that's the case, error if so)

**Comment by actflower** [comment]
Hi @danlester! I've implemented improvements to provide better feedback when org tokens aren't working properly.

## What's been fixed:

✅ **Token validation now tests repository access** - When you add a token, it immediately checks if it can access repositories and shows a count of accessible repos

✅ **Error display in account page** - Each token now shows:
- 📚 Number of accessible repositories (if successful)
- ⚠️ Warning if the token can't access repos
- ❌ Error messages if the token fails during repository fetching

✅ **Helpful warnings when adding tokens** - If a token can't access repos, you'll see a warning explaining common causes:
- Missing SSO authorization
- Incorrect permissions
- Organization restrictions on token types

✅ **Persistent error tracking** - Error states are saved so you can see what went wrong even after refreshing

## How this helps:

When you add an org token that's not configured correctly, you'll now see immediate feedback about what's wrong. For example:
- "Cannot access repositories (401)" - Usually means SSO authorization is needed
- "Cannot access repositories (403)" - Usually means insufficient permissions
- "0 repos accessible" - Token works but has no repo access configured

The changes have been committed to the dev branch and should help identify why your org token wasn't showing repositories. Try adding the token again and you should see helpful error messages if something's wrong!

**Comment by danlester** [comment]
Still can't see repo counts - for existing tokens anyway, haven't tried adding new tokens

**Comment by actflower** [comment]
Hi @danlester! I've fixed the repo count display issue for existing tokens. 

## What was the problem?
The `getAllTokens()` method wasn't including the `repoCount` and error properties when returning token data, so even though the repo counts were stored, they weren't being displayed in the UI.

## What's been fixed:

✅ **Fixed `getAllTokens()` method** - Now properly includes `repoCount`, `repoAccessError`, `lastError`, and `lastErrorTime` properties

✅ **Added automatic repo count refresh** - When you open the Manage Tokens UI, it will automatically fetch and update repo counts for any existing tokens that don't have them yet

✅ **Display updates immediately** - The UI now properly shows:
- 📚 Number of accessible repositories for each token
- ⚠️ Warning messages if there are access issues  
- ❌ Error messages if the token fails

## How to verify:
1. Open the Manage Tokens UI (click your profile icon → Manage Tokens)
2. You should now see repo counts displayed for all your tokens
3. If any existing tokens didn't have counts before, they'll be fetched automatically when you open the UI

The changes have been pushed to the dev branch. Let me know if you're still not seeing the repo counts!

**Comment by actflower** [comment]
Fixed! I've switched back to using `/user/repos` for all tokens (including organization-specific ones).

## What was the problem?
The code was using `/orgs/{org}/repos` for organization tokens, which only returns **public repositories**. The `/user/repos` endpoint returns **all repositories accessible to the authenticated token**, including both public and private repos.

## Changes made:
- Updated token validation in `tokenManager.js` to use `/user/repos` for counting accessible repos
- Updated repository fetching in `api.js` to use `/user/repos` for all token types
- This ensures private repositories are included in both the count display and the actual repository list

The repository counts should now correctly show the total of both public and private repositories that each token can access. The changes have been pushed to the dev branch.
